version: "3.4"
services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.40.3@sha256:36f7953fb618f99bfb456c80e7ec94432d8af3c1bfcc034e46a018cc64b534b7
    container_name: plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    networks:
      - brandin-media-stack
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${CONFIG_ROOT}/config/plex/db:/config 
      - ${CONFIG_ROOT}/config/plex/transcode:/transcode
      - ${MEDIA_ROOT}/complete:/data 
  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:3.0.10@sha256:4f69472a0cdea29e23967db6a3395487539b759def3920327d1f49ae00b9dfd4
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID} 
      - TZ=${TZ} 
    ports:
      - 8989:8989
    networks:
      - brandin-media-stack
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/config/sonarr:/config
      - ${MEDIA_ROOT}/complete/tv:/tv 
      - ${MEDIA_ROOT}/downloads:/downloads 
  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.6.0@sha256:79053c07400eec909d04ac97db760c30bf61471ec37465a50f126a3c825a92bc    
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID} 
      - TZ=${TZ} 
    ports:
      - 7878:7878
    networks:
      - brandin-media-stack
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/config/radarr:/config 
      - ${MEDIA_ROOT}/complete/movies:/movies
      - ${MEDIA_ROOT}/downloads:/downloads 
  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: linuxserver/overseerr:1.33.2@sha256:a21b9f6cce4fa7040a32a9feb77a1902e792cd3716acf695ee416862dc22c6a4
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    networks:
      - brandin-media-stack
    volumes:
      - ${CONFIG_ROOT}/config/overseerr:/config 
    ports:
      - 5055:5055
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-swag
  swag:
    image: linuxserver/swag:2.11.0@sha256:81d085774542465fb128b8d8b57939ec8352fef3b80a30c1ed59ee9a32701941
    container_name: swag
    networks:
      - brandin-media-stack
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${SWAG_URL}
      - VALIDATION=http
      - SUBDOMAINS=www,overseerr #optional
    volumes:
      - ${CONFIG_ROOT}/config/swag:/config
    ports:
      - 443:443
      - 80:80 
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:2.14.2@sha256:22328b7ec50d9e005a96805ad67cd9ace138960eae9dcda6265ef7baad5263e9
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    networks:
      - brandin-media-stack
    volumes:
      - ${CONFIG_ROOT}/config/tautulli:/config
  # https://docs.linuxserver.io/images/docker-bazarr
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:1.4.3@sha256:6fb83511c0dca70a400fde79cb45ed59c4f66ea30dcba8c6f9274f01d77e5aef
    restart: unless-stopped
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
      - UMASK_SET=022 #optional
    ports:
      - 6767:6767
    networks:
      - brandin-media-stack
    volumes:
      - ${CONFIG_ROOT}/config/bazarr:/config 
      - ${MEDIA_ROOT}/complete/movies:/movies 
      - ${MEDIA_ROOT}/complete/tv:/tv
  # https://docs.linuxserver.io/images/docker-duckdns
  duckdns:
    image: linuxserver/duckdns:version-256b24bf@sha256:f8cc95c15a64a5c90e29640b77260d5692c0ad92dc57f97c374d26eb6eb43204
    container_name: duckdns
    network_mode: host 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} 
      - SUBDOMAINS=${DUCK_DNS_SUBDOMAINS}
      - TOKEN=${DUCK_DNS_TOKEN}
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - ${CONFIG_ROOT}/config/duckdns:/config 
    restart: unless-stopped
  # https://www.authelia.com/integration/deployment/docker
  authelia:
    container_name: authelia
    image: authelia/authelia:4.38@sha256:491745686a70863b33a9978795e13fdeb8bc82e4fcfa456bf30f788827114cb0
    restart: unless-stopped
    networks:
      - brandin-media-stack
    expose:
      - 9091
    volumes:
      - ${CONFIG_ROOT}/config/authelia:/config
    environment:
      - TZ=${TZ}
  # https://docs.linuxserver.io/images/docker-sabnzbd/
  sabnzbd:
    image: linuxserver/sabnzbd:4.3.2@sha256:ab89014bb120a092a67c3702b38a9c614e8d06fd6f62225edb8ce770f26fd08a
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/config/sabnzbd:/config
      - ${MEDIA_ROOT}/downloads:/downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - brandin-media-stack
networks:
  brandin-media-stack:
    name: brandin-media-stack