version: "3.4"
services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.40.3@sha256:c0d40a44980f33169fb341a6aa7cb45dc294e2817537b81d0677a15288b05c99
    container_name: plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    networks:
      - brandin-media-stack
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${CONFIG_ROOT}/config/plex/db:/config 
      - ${CONFIG_ROOT}/config/plex/transcode:/transcode
      - ${MEDIA_ROOT}/complete:/data 
  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:3.0.10@sha256:4f69472a0cdea29e23967db6a3395487539b759def3920327d1f49ae00b9dfd4
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID} 
      - TZ=${TZ} 
    ports:
      - 8989:8989
    networks:
      - brandin-media-stack
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/config/sonarr:/config
      - ${MEDIA_ROOT}/complete/tv:/tv 
      - ${MEDIA_ROOT}/downloads:/downloads 
  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.7.0@sha256:c5b78b1f1e8556d781788194c4ee2b87ca7e3620b701bfce31499e60ee50eca3    
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID} 
      - TZ=${TZ} 
    ports:
      - 7878:7878
    networks:
      - brandin-media-stack
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/config/radarr:/config 
      - ${MEDIA_ROOT}/complete/movies:/movies
      - ${MEDIA_ROOT}/downloads:/downloads 
  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: linuxserver/overseerr:1.33.2@sha256:ed32f910825e2432922e1add36da8da2d1c3e9462fad6f3586a2af5a4a23f832
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    networks:
      - brandin-media-stack
    volumes:
      - ${CONFIG_ROOT}/config/overseerr:/config 
    ports:
      - 5055:5055
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-swag
  swag:
    image: linuxserver/swag:2.11.0@sha256:676272daa592f399634f90b0de2aa0e4614fd8651f0b1eb7b1377479b53422ee
    container_name: swag
    networks:
      - brandin-media-stack
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${SWAG_URL}
      - VALIDATION=http
      - SUBDOMAINS=www,overseerr #optional
    volumes:
      - ${CONFIG_ROOT}/config/swag:/config
    ports:
      - 443:443
      - 80:80 
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:2.14.3@sha256:f25b902c4fa015657f08392c3169ab06d55bb0467789f427e599917264decebc
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    networks:
      - brandin-media-stack
    volumes:
      - ${CONFIG_ROOT}/config/tautulli:/config
  # https://docs.linuxserver.io/images/docker-bazarr
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:1.4.3@sha256:a113dca480a1e223c1ea62261650ebb56d659a8af5455e50ab5ac1f13ef21707
    restart: unless-stopped
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
      - UMASK_SET=022 #optional
    ports:
      - 6767:6767
    networks:
      - brandin-media-stack
    volumes:
      - ${CONFIG_ROOT}/config/bazarr:/config 
      - ${MEDIA_ROOT}/complete/movies:/movies 
      - ${MEDIA_ROOT}/complete/tv:/tv
  # https://docs.linuxserver.io/images/docker-duckdns
  duckdns:
    image: linuxserver/duckdns:version-256b24bf@sha256:f8cc95c15a64a5c90e29640b77260d5692c0ad92dc57f97c374d26eb6eb43204
    container_name: duckdns
    network_mode: host 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} 
      - SUBDOMAINS=${DUCK_DNS_SUBDOMAINS}
      - TOKEN=${DUCK_DNS_TOKEN}
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - ${CONFIG_ROOT}/config/duckdns:/config 
    restart: unless-stopped
  # https://www.authelia.com/integration/deployment/docker
  authelia:
    container_name: authelia
    image: authelia/authelia:4.38@sha256:491745686a70863b33a9978795e13fdeb8bc82e4fcfa456bf30f788827114cb0
    restart: unless-stopped
    networks:
      - brandin-media-stack
    expose:
      - 9091
    volumes:
      - ${CONFIG_ROOT}/config/authelia:/config
    environment:
      - TZ=${TZ}
  # https://docs.linuxserver.io/images/docker-sabnzbd/
  sabnzbd:
    image: linuxserver/sabnzbd:4.3.2@sha256:134199776cc6e750896c40a2eae547713ecd8c1bc7912369046b19382283c176
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/config/sabnzbd:/config
      - ${MEDIA_ROOT}/downloads:/downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - brandin-media-stack
networks:
  brandin-media-stack:
    name: brandin-media-stack