version: "3.4"
services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.40.4@sha256:97d5d64e10850c67a2a694374b536a02f0e62bfae3b292ccfb8c07d6b1f0a79f
    container_name: plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    networks:
      - sofa-squad
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${CONFIG_ROOT}/config/plex/db:/config
      - ${CONFIG_ROOT}/config/plex/transcode:/transcode
      - ${MEDIA_ROOT}/complete:/data
  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:3.0.10@sha256:4f69472a0cdea29e23967db6a3395487539b759def3920327d1f49ae00b9dfd4
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    networks:
      - sofa-squad
    volumes:
      - /etc/localtime:/etc/localtime
      - ${CONFIG_ROOT}/config/sonarr:/config
      - ${MEDIA_ROOT}/complete/tv:/tv
      - ${MEDIA_ROOT}/downloads:/downloads
  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.8.3@sha256:938281e82a91da0115d0f8b0a2260acf0f07052c8c78dfaf7e407c843ae242f5
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 7878:7878
    networks:
      - sofa-squad
    volumes:
      - /etc/localtime:/etc/localtime
      - ${CONFIG_ROOT}/config/radarr:/config
      - ${MEDIA_ROOT}/complete/movies:/movies
      - ${MEDIA_ROOT}/downloads:/downloads
  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: linuxserver/overseerr:1.33.2@sha256:3543bcc57aaa74842d8d88c6a0a6805b166d89e2dfc0db74b703ee59f8d7266e
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-swag
  swag:
    image: linuxserver/swag:2.11.0@sha256:9aefabdc07d7d918cbf0d6aec0a42fa9d933e82d108798cee7c5bc9919c64bd1
    container_name: swag
    networks:
      - sofa-squad
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${SWAG_URL}
      - VALIDATION=http
      - SUBDOMAINS=www,overseerr #optional
      - DOCKER_MODS=linuxserver/mods:swag-dashboard
    volumes:
      - ${CONFIG_ROOT}/config/swag:/config
    ports:
      - 443:443
      - 80:80
      - 81:81
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:2.14.3@sha256:05521bf5fbab6d9297fed5ae8525b4ff24dec3773bce40c0d0b831a8708a13e2
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/tautulli:/config
  # https://docs.linuxserver.io/images/docker-bazarr
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:1.4.3@sha256:aa904c142512b64e98b0abd038bf8b07e1b0e8cf3a14a805cb9ae4df9415b933
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    ports:
      - 6767:6767
    networks:
      - sofa-squad
    volumes:
      - ${CONFIG_ROOT}/config/bazarr:/config
      - ${MEDIA_ROOT}/complete/movies:/movies
      - ${MEDIA_ROOT}/complete/tv:/tv
  # https://docs.linuxserver.io/images/docker-duckdns
  duckdns:
    image: linuxserver/duckdns:version-256b24bf@sha256:f8cc95c15a64a5c90e29640b77260d5692c0ad92dc57f97c374d26eb6eb43204
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=${DUCK_DNS_SUBDOMAINS}
      - TOKEN=${DUCK_DNS_TOKEN}
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - ${CONFIG_ROOT}/config/duckdns:/config
    restart: unless-stopped
  # https://www.authelia.com/integration/deployment/docker
  authelia:
    container_name: authelia
    image: authelia/authelia:4.38@sha256:1af32be812f041c1f3a91190faf9a022e586b185251d26a29bcdf7982bcb3bc7
    restart: unless-stopped
    networks:
      - sofa-squad
    expose:
      - 9091
    volumes:
      - ${CONFIG_ROOT}/config/authelia:/config
    environment:
      - TZ=${TZ}
  # https://docs.linuxserver.io/images/docker-sabnzbd/
  sabnzbd:
    image: linuxserver/sabnzbd:4.3.2@sha256:dda700370ad4281d8ffda4fbdad8ac3f720a2829936eafc794fca652095ed4be
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/config/sabnzbd:/config
      - ${MEDIA_ROOT}/downloads:/downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - sofa-squad
networks:
  sofa-squad:
    name: sofa-squad
