version: "3.4"
services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.40.2@sha256:114bc1566b442144552843fe43c45ca1a4fb023b46ce2c75485d611792e45519
    container_name: plex
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    networks:
      - brandin-media-stack
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${CONFIG_ROOT}/config/plex/db:/config 
      - ${CONFIG_ROOT}/config/plex/transcode:/transcode
      - ${MEDIA_ROOT}/complete:/data 
  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:3.0.10@sha256:4f69472a0cdea29e23967db6a3395487539b759def3920327d1f49ae00b9dfd4
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID} 
      - TZ=${TZ} 
    ports:
      - 8989:8989
    networks:
      - brandin-media-stack
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/config/sonarr:/config
      - ${MEDIA_ROOT}/complete/tv:/tv 
      - ${MEDIA_ROOT}/downloads:/downloads 
  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.4.6@sha256:1c2f2abbabd19c47549a4e7c3315402a3a4c37f141ba56cef3395ec6b292a015    
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID} 
      - TZ=${TZ} 
    ports:
      - 7878:7878
    networks:
      - brandin-media-stack
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/config/radarr:/config 
      - ${MEDIA_ROOT}/complete/movies:/movies
      - ${MEDIA_ROOT}/downloads:/downloads 
  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: linuxserver/overseerr:1.33.2@sha256:711c465b65d36a01580f995043a240eedaac0aa31321a8d95fa8f29f0ff8299d
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    networks:
      - brandin-media-stack
    volumes:
      - ${CONFIG_ROOT}/config/overseerr:/config 
    ports:
      - 5055:5055
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-swag
  swag:
    image: linuxserver/swag:2.10.0@sha256:488f26871e89fa56d2e1f19def26aec1efaeadc1f31e96e1628db77f2a521e9d
    container_name: swag
    networks:
      - brandin-media-stack
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${SWAG_URL}
      - VALIDATION=http
      - SUBDOMAINS=www,overseerr #optional
    volumes:
      - ${CONFIG_ROOT}/config/swag:/config
    ports:
      - 443:443
      - 80:80 
    restart: unless-stopped
  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:2.13.4@sha256:8d14fb0e6a0101970574963ee5e0de0822b5a93d4e8a0b033e870b7b039661ae
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    networks:
      - brandin-media-stack
    volumes:
      - ${CONFIG_ROOT}/config/tautulli:/config
  # https://docs.linuxserver.io/images/docker-bazarr
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:1.4.2@sha256:2c9269dd25c62d46e679a035849f32e963152ec44000e30f008d211a2f70e80c
    restart: unless-stopped
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
      - UMASK_SET=022 #optional
    ports:
      - 6767:6767
    networks:
      - brandin-media-stack
    volumes:
      - ${CONFIG_ROOT}/config/bazarr:/config 
      - ${MEDIA_ROOT}/complete/movies:/movies 
      - ${MEDIA_ROOT}/complete/tv:/tv
  # https://docs.linuxserver.io/images/docker-duckdns
  duckdns:
    image: linuxserver/duckdns:version-256b24bf@sha256:f8cc95c15a64a5c90e29640b77260d5692c0ad92dc57f97c374d26eb6eb43204
    container_name: duckdns
    network_mode: host 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} 
      - SUBDOMAINS=${DUCK_DNS_SUBDOMAINS}
      - TOKEN=${DUCK_DNS_TOKEN}
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - ${CONFIG_ROOT}/config/duckdns:/config 
    restart: unless-stopped
  # https://www.authelia.com/integration/deployment/docker
  authelia:
    container_name: authelia
    image: authelia/authelia:4.38@sha256:19375b10024caeef4e0b119a6247beae84cbaa02c846cfd750e92dea910d4b6a
    restart: unless-stopped
    networks:
      - brandin-media-stack
    expose:
      - 9091
    volumes:
      - ${CONFIG_ROOT}/config/authelia:/config
    environment:
      - TZ=${TZ}
  # https://docs.linuxserver.io/images/docker-sabnzbd/
  sabnzbd:
    image: linuxserver/sabnzbd:4.3.1@sha256:8ee3019ca921f6c46294f2e363453fa41875d309c7e68028a73f8169eb35a691
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/config/sabnzbd:/config
      - ${MEDIA_ROOT}/downloads:/downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - brandin-media-stack
networks:
  brandin-media-stack:
    name: brandin-media-stack