name: Versioning
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Conventional Changelog CLI
      run: npm install -g conventional-changelog-cli

    - name: Generate changelog
      run: conventional-changelog -p angular -i CHANGELOG.md -s

    - name: Set up Git
      run: |
        git config user.email "brandincanfield@gmail.com"
        git config user.name "B"
        git add CHANGELOG.md
        git commit -m "chore(release): bump version based on commit messages"
        git push

    - name: Determine the new version
      id: bump_version
      run: |
        current_version=$(grep -o -E "[0-9]+\.[0-9]+\.[0-9]+" CHANGELOG.md | head -n 1)
        echo "::set-output name=new_version::$current_version"

    - name: Create and push a new tag
      run: |
        git tag ${{ steps.bump_version.outputs.new_version }}
        git push origin --tags
