name: Create Git Tag

on:
  push:
    branches:
      - test

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract version and commit message
      id: extract-info
      run: |
        version=$(cat version.txt)  # Replace with the path to your version file
        commit_message=$(git log -1 --pretty=%s)
        commit_body=$(git log -1 --pretty=%b)
        echo "::set-output name=version::$version"
        echo "::set-output name=commit_message::$commit_message"

    - name: Determine version increment
      id: increment-version
      run: |
        commit_body="${{ steps.extract-info.outputs.commit_body }}"
        echo "BRANDIN $commit_body"
        if [[ $commit_body == *"major"* ]]; then
          version_parts=($(echo ${{ steps.extract-info.outputs.version }} | tr '.' ' '))
          major=$((version_parts[0] + 1))
          new_version="$major.0.0"
        elif [[ $commit_body == *"minor"* ]]; then
          version_parts=($(echo ${{ steps.extract-info.outputs.version }} | tr '.' ' '))
          major=${version_parts[0]}
          minor=$((version_parts[1] + 1))
          new_version="$major.$minor.0"
        else
          version_parts=($(echo ${{ steps.extract-info.outputs.version }} | tr '.' ' '))
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=$((version_parts[2] + 1))
          new_version="$major.$minor.$patch"
        fi
        echo "::set-output name=new_version::$new_version"

    - name: Update version.txt
      run: |
        echo "${{ steps.increment-version.outputs.new_version }}" > version.txt
        git config user.name "bcanfield"
        git config user.email "brandincanfield@gmail.com"
        git add version.txt
        # git commit -m "Version ${{ steps.increment-version.outputs.new_version }}"
        # git push

    - name: Update changelog.md
      run: |
        echo "## Version ${{ steps.increment-version.outputs.new_version }}" >> changelog.md
        echo "- Commit Message: ${{ steps.extract-info.outputs.commit_message }}" >> changelog.md
        echo "- Commit Body: ${{ steps.extract-info.outputs.commit_body }}" >> changelog.md
        echo "" >> changelog.md
        git add changelog.md
        git commit -m "Version ${{ steps.increment-version.outputs.new_version }}"
        git push

    - name: Create Git Tag
      run: |
        git tag -a -m "Version ${{ steps.increment-version.outputs.new_version }} ${{ steps.extract-info.outputs.commit_message }}" v${{ steps.increment-version.outputs.new_version }}
        git push origin v${{ steps.increment-version.outputs.new_version }}

